/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as InvertersRouteImport } from './routes/inverters'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as PoweredByJetfloRouteImport } from './routes/powered-by-jetflo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const InvertersRoute = InvertersRouteImport.update({
  id: '/inverters',
  path: '/inverters',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const PoweredByJetfloRoute = PoweredByJetfloRouteImport.update({
  id: '/powered-by-jetflo',
  path: '/powered-by-jetflo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/inverters': typeof InvertersRoute
  '/kits': typeof KitsRoute
  '/powered-by-jetflo': typeof PoweredByJetfloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/inverters': typeof InvertersRoute
  '/kits': typeof KitsRoute
  '/powered-by-jetflo': typeof PoweredByJetfloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/inverters': typeof InvertersRoute
  '/kits': typeof KitsRoute
  '/powered-by-jetflo': typeof PoweredByJetfloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/inverters' | '/kits' | '/powered-by-jetflo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/inverters' | '/kits' | '/powered-by-jetflo'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/inverters'
    | '/kits'
    | '/powered-by-jetflo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  InvertersRoute: typeof InvertersRoute
  KitsRoute: typeof KitsRoute
  PoweredByJetfloRoute: typeof PoweredByJetfloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inverters': {
      id: '/inverters'
      path: '/inverters'
      fullPath: '/inverters'
      preLoaderRoute: typeof InvertersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powered-by-jetflo': {
      id: '/powered-by-jetflo'
      path: '/powered-by-jetflo'
      fullPath: '/powered-by-jetflo'
      preLoaderRoute: typeof PoweredByJetfloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  InvertersRoute: InvertersRoute,
  KitsRoute: KitsRoute,
  PoweredByJetfloRoute: PoweredByJetfloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
